version: '2.1'
services:
  zookeeper:
    image: mgarmes/kafka
    environment:
      COMPONENT: zookeeper
    volumes:
      - ./zookeeper:/opt/kafka/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: mgarmes/kafka
    ports:
      - "9092:9092"
    environment:
      COMPONENT: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://:19092,LISTENER_DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_LOG_DIRS: /opt/kafka/kafka/data
    volumes:
      - ./kafka-data:/opt/kafka/kafka/data
    depends_on:
      - zookeeper
